# Generated by Django 4.0 on 2023-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='room',
            new_name='post',
        ),
    ]
